name: "Deploy CodigoFacilito"

on:
  push:
    branches: ["master"]

jobs:
  1_deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hacemos un pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Generar Binario"
      - run: echo "Publicar version"

  2_deploy-codigofacilito:
    needs: 1_deploy-codigofacilito
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "segundo job"