name: "Deploy CodigoFacilito"

on:
  push:
    branches: ["master"]

jobs:
  first_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hacemos un pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Generar Binario"
      - run: echo "Publicar version"

  second_deploy:
    needs: first_deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "segundo job"